/*
    Warning - this file was autogenerated by genparse
    DO NOT EDIT - any changes will be lost
*/

#include "at_cmd_tmp.h"

#include <ctype.h>
#include <panic.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <util.h> /* hash and compare */

#if (defined TEST_HARNESS || defined DISPLAY_AT_CMDS)
#include <stdio.h>
#endif

typedef const uint8 *ptr;

static __inline__ char my_toupper(char c)
{ return 'a' <= c && c <= 'z' ? c +'A'-'a' : c; }

static ptr skip1(ptr s, ptr e)
{
  if(s)
    while(s != e && (*s == ' ' || *s == '\t'))
      ++s;
  return s;
}

static ptr match1(ptr s, ptr e)
{ return s && s != e && (*s == '\r' || *s == '\n') ? s+1 : 0; }

#ifdef TEST_HARNESS
static void printString(const char *name, const struct sequence *s)
{
  uint16 i;
  printf(" %s='", name);
  for(i = 0; i < s->length; ++i) putchar(s->data[i]);
  printf("'");
}
#endif

static __inline__ ptr skipQuote(ptr p, ptr e)
{ return p && p != e && *p == '"' ? p+1 : p; }

static const int isStringTable[] =
{
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,0,0,1,0,0,0,0,0,0,1,1,0,1,0,1,
    1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0
};

static __inline__ int isString(char c)
{
    return (c & ~0x7F) == 0 && isStringTable[(int)c];
}

static ptr getString(ptr p, ptr e, struct sequence *res)
{
  p = skipQuote(p, e);
  if(p)
  {
    ptr s = p;
    while(p != e && isString(*p)) ++p;
    if(p != s)
    {
        res->data = s;
        res->length = p - s;
        return skipQuote(p, e);
    }
    else
    {
        p = skipQuote(p, e);
        if (*p==',' || *p == '\r')
        {
            res->data = 0;
            res->length = 0;
            return p;
        }
    }
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr skipOnce1(ptr s, ptr e)
{
  if(s)
  {
    if(s != e && (*s == ',' || *s == ';'))
      ++s;
  }
  return s;
}

static ptr getWildString(ptr p, ptr e, struct sequence *res)
{
  if(p)
  {
    ptr s = p;
    p = (uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16) (e - p));
    if (!p) p = (uint8*)UtilFind(0xFFFF, '\n', (const uint16*)p, 0, 1, e - p);
    if (!p) p = e;
    res->data = s;
    res->length = p - s;
    return p;
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr findEndOfPacket(ptr s, ptr e)
{
  /*
     Returns
     0   if the buffer holds an incomplete packet
     s+1 if the buffer holds an invalid packet
     end of the first packet otherwise
  */
  if(s == e) return 0;

  if(*s == '\r')
  {
    /* expecting <cr> <lf> ... <cr> <lf> */
    if(e-s >= 4)
    {
      if(s[1] == '\n' && s[2] != '\r')
      {
        ptr p = s+2;
        if(*p != '\r')
        {
#ifndef TEST_HARNESS
        p = (const uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16)(e-p));
#endif
#ifdef TEST_HARNESS
		   while(p != e && *p != '\r') p++;
#endif
        return p == 0 || p + 1 == e ? 0 /* no terminator yet */
             : p[1] == '\n' ? p+2 /* valid */
             : s+1 ; /* invalid terminator */
         }
         else
             return s+1;
      }
      else
      {
        return s+1;
      }
    }
    else
    {
      /* Can't tell yet */
      return 0;
    }
  }
  else
  {
    /* expecting ... <cr> */
    ptr p = s;
    while(p != e && (*p == ' ' || *p == '\n' || *p == '\0' || *p == '\t')) ++p;
    if(p != e && *p == '\r') return s+1;
    while(p != e && *p != '\r') ++p;
    return p == e ? 0 : p+1;
  }
}

#ifndef TEST_HARNESS
#ifdef __XAP__
uint16 parseSource(Source rfcDataIn, Task task)
{
  ptr s = SourceMap(rfcDataIn);
  ptr e = s + SourceSize(rfcDataIn);
  ptr p = parseData(s, e, task);
  if(p != s)
  {
    SourceDrop(rfcDataIn, (uint16) (p - s));
    return 1;
  }
  else
  {
    return 0;
  }
}
#endif
#endif

typedef struct {
  char c;
  int to;
} Arc;

static const Arc arcs[] = {
  { '\t', 0 },
  { ' ', 0 },
  { 'A', 1 },
  { 'T', 2 },
  { '\t', 2 },
  { ' ', 2 },
  { '+', 3 },
  { '\t', 3 },
  { ' ', 3 },
  { 'A', 4 },
  { 'C', 5 },
  { 'M', 6 },
  { 'R', 7 },
  { 'S', 8 },
  { 'V', 9 },
  { 'W', 10 },
  { 'C', 11 },
  { 'D', 12 },
  { 'I', 13 },
  { 'M', 14 },
  { 'C', 15 },
  { 'D', 16 },
  { 'P', 17 },
  { 'R', 18 },
  { 'S', 19 },
  { 'D', 20 },
  { 'C', 21 },
  { 'D', 22 },
  { 'P', 23 },
  { 'G', 24 },
  { 'I', 25 },
  { 'R', 26 },
  { 'O', 27 },
  { 'S', 28 },
  { 'N', 29 },
  { 'T', 30 },
  { 'O', 31 },
  { 'S', 32 },
  { 'L', 33 },
  { 'S', 34 },
  { 'P', 35 },
  { 'B', 36 },
  { 'N', 37 },
  { 'S', 38 },
  { 'O', 39 },
  { 'S', 40 },
  { 'B', 41 },
  { 'I', 42 },
  { 'M', 43 },
  { 'S', 44 },
  { 'N', 45 },
  { 'N', 46 },
  { 'N', 47 },
  { 'C', 48 },
  { 'C', 49 },
  { 'I', 50 },
  { 'N', 51 },
  { 'C', 52 },
  { 'Y', 53 },
  { 'T', 54 },
  { 'D', 55 },
  { 'D', 56 },
  { 'M', 57 },
  { 'S', 58 },
  { 'N', 59 },
  { 'C', 60 },
  { 'N', 61 },
  { 'N', 62 },
  { '\t', 43 },
  { ' ', 43 },
  { ':', -1 },
  { '=', -1 },
  { '\t', 44 },
  { ' ', 44 },
  { ':', -2 },
  { '=', -2 },
  { '\t', 45 },
  { ' ', 45 },
  { ':', 63 },
  { '=', 63 },
  { 'M', 64 },
  { '\t', 47 },
  { '\n', -3 },
  { '\r', -3 },
  { ' ', 47 },
  { '\t', 48 },
  { '\n', -4 },
  { '\r', -4 },
  { ' ', 48 },
  { '\t', 49 },
  { ' ', 49 },
  { ':', -5 },
  { '=', -5 },
  { '\t', 50 },
  { ' ', 50 },
  { ':', -6 },
  { '=', -6 },
  { '\t', 51 },
  { '\n', -7 },
  { '\r', -7 },
  { ' ', 51 },
  { ':', -8 },
  { '=', -8 },
  { '\t', 52 },
  { '\n', -9 },
  { '\r', -9 },
  { ' ', 52 },
  { '\t', 53 },
  { '\n', -10 },
  { '\r', -10 },
  { ' ', 53 },
  { '\t', 54 },
  { '\n', -11 },
  { '\r', -11 },
  { ' ', 54 },
  { '\t', 55 },
  { '\n', -12 },
  { '\r', -12 },
  { ' ', 55 },
  { '\t', 56 },
  { '\n', -13 },
  { '\r', -13 },
  { ' ', 56 },
  { '\t', 57 },
  { '\n', -14 },
  { '\r', -14 },
  { ' ', 57 },
  { '\t', 58 },
  { '\n', -15 },
  { '\r', -15 },
  { ' ', 58 },
  { '\t', 59 },
  { ' ', 59 },
  { ':', -16 },
  { '=', -16 },
  { '\t', 60 },
  { '\n', -17 },
  { '\r', -17 },
  { ' ', 60 },
  { '\t', 61 },
  { ' ', 61 },
  { ':', -18 },
  { '=', -18 },
  { '\t', 62 },
  { ' ', 62 },
  { ':', -19 },
  { '=', -19 },
  { '\t', 63 },
  { '\n', -20 },
  { '\r', -20 },
  { ' ', 63 },
  { '?', 65 },
  { '\t', 64 },
  { ' ', 64 },
  { ':', -21 },
  { '=', -21 },
  { '\t', 66 },
  { '\n', -20 },
  { '\r', -20 },
  { ' ', 66 },
  { '?', 65 },
  { '\t', 66 },
  { '\n', -20 },
  { '\r', -20 },
  { ' ', 66 },
};

static const Arc *const states[68] = {
  &arcs[0],
  &arcs[3],
  &arcs[4],
  &arcs[7],
  &arcs[16],
  &arcs[18],
  &arcs[20],
  &arcs[25],
  &arcs[26],
  &arcs[29],
  &arcs[31],
  &arcs[32],
  &arcs[33],
  &arcs[34],
  &arcs[35],
  &arcs[36],
  &arcs[37],
  &arcs[38],
  &arcs[39],
  &arcs[40],
  &arcs[41],
  &arcs[44],
  &arcs[45],
  &arcs[46],
  &arcs[48],
  &arcs[50],
  &arcs[51],
  &arcs[52],
  &arcs[53],
  &arcs[54],
  &arcs[55],
  &arcs[56],
  &arcs[57],
  &arcs[58],
  &arcs[59],
  &arcs[60],
  &arcs[61],
  &arcs[62],
  &arcs[63],
  &arcs[64],
  &arcs[65],
  &arcs[66],
  &arcs[67],
  &arcs[68],
  &arcs[72],
  &arcs[76],
  &arcs[80],
  &arcs[81],
  &arcs[85],
  &arcs[89],
  &arcs[93],
  &arcs[97],
  &arcs[103],
  &arcs[107],
  &arcs[111],
  &arcs[115],
  &arcs[119],
  &arcs[123],
  &arcs[127],
  &arcs[131],
  &arcs[135],
  &arcs[139],
  &arcs[143],
  &arcs[147],
  &arcs[152],
  &arcs[156],
  &arcs[161],
  &arcs[165],
};

static uint16 matchLiteral(ptr s, ptr e, Task task)
{ s=s; e=e; task=task; return 0; }

ptr parseData(ptr s, ptr e, Task task)
{
  ptr p;

#ifdef DISPLAY_AT_CMDS
  {
  	ptr c = s;
    printf("\nreceived: ");
  	while (c != e)
  	{
		if (*c == '\r')			printf("\\r");
		else if (*c == '\n') 	printf("\\n");
		else 					putchar(*c);

		c++;
  	}
  }
#endif

#ifdef TEST_HARNESS
  task = task;
#endif
  for(; (p = findEndOfPacket(s, e)) != 0; s = p)
  {
    if(p == s+1)
    {
      /* Silently discard one character; no packets are that short */
      continue;
    }
    else if(matchLiteral(s, p, task))
    {
      continue;
    }
    else
    {
      union {
        struct set_volume_microphone set_volume_microphone;
        struct set_volume_speaker set_volume_speaker;
        struct virtual_incoming_call virtual_incoming_call;
        struct sms_new_message_ind sms_new_message_ind;
        struct a2dp_signal_connect_req a2dp_signal_connect_req;
        struct slc_connect_req slc_connect_req;
        struct set_phonebook_index set_phonebook_index;
        struct write_pin write_pin;
        struct write_local_name write_local_name;
      } u, *uu = &u;
      int state = 0;
      ptr t = s;
      while(t != e && state >= 0)
      {
        char m = my_toupper((char) *t);
        const Arc *a = states[state];
        const Arc *const last_a = states[state+1];
#ifndef TEST_HARNESS
        a = (const Arc *) (void *) UtilFind(0xFFFF, (uint16) m, (const uint16 *) (void *) &a[0].c, 0, sizeof(Arc), (uint16) (last_a - a));
#endif
#ifdef TEST_HARNESS
        while(a != last_a && a->c != m) a++;
#endif
        /*lint -e{801} suppress goto is deprecated */
        if(!a) goto unrecognised;
        state = a->to;
        ++t;
      }
      switch(-state)
      {
        case 1:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->set_volume_microphone.volume), e), e))
          {
#ifndef TEST_HARNESS
            set_volume_microphone(task, &uu->set_volume_microphone);
#endif
#ifdef TEST_HARNESS
            printf("Called set_volume_microphone");
            printf(" volume=%d", uu->set_volume_microphone.volume);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 2:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->set_volume_speaker.volume), e), e))
          {
#ifndef TEST_HARNESS
            set_volume_speaker(task, &uu->set_volume_speaker);
#endif
#ifdef TEST_HARNESS
            printf("Called set_volume_speaker");
            printf(" volume=%d", uu->set_volume_speaker.volume);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 3:
          if(t)
          {
#ifndef TEST_HARNESS
            audio_connect_req(task);
#endif
#ifdef TEST_HARNESS
            printf("Called audio_connect_req");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 4:
          if(t)
          {
#ifndef TEST_HARNESS
            audio_disconnect_req(task);
#endif
#ifdef TEST_HARNESS
            printf("Called audio_disconnect_req");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 5:
          if(match1(skip1(getString(skip1(t, e), e, &uu->virtual_incoming_call.callerid), e), e))
          {
#ifndef TEST_HARNESS
            virtual_incoming_call(task, &uu->virtual_incoming_call);
#endif
#ifdef TEST_HARNESS
            printf("Called virtual_incoming_call");
            printString("callerid", &uu->virtual_incoming_call.callerid);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 6:
          if(match1(skip1(getWildString(skip1(skipOnce1(skip1(getString(skip1(t, e), e, &uu->sms_new_message_ind.sender), e), e), e), e, &uu->sms_new_message_ind.text), e), e))
          {
#ifndef TEST_HARNESS
            sms_new_message_ind(task, &uu->sms_new_message_ind);
#endif
#ifdef TEST_HARNESS
            printf("Called sms_new_message_ind");
            printString("sender", &uu->sms_new_message_ind.sender);
            printString("text", &uu->sms_new_message_ind.text);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 7:
          if(t)
          {
#ifndef TEST_HARNESS
            a2dp_signal_connect_req_to_ags(task);
#endif
#ifdef TEST_HARNESS
            printf("Called a2dp_signal_connect_req_to_ags");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 8:
          if(match1(skip1(getString(skip1(t, e), e, &uu->a2dp_signal_connect_req.bdaddr), e), e))
          {
#ifndef TEST_HARNESS
            a2dp_signal_connect_req(task, &uu->a2dp_signal_connect_req);
#endif
#ifdef TEST_HARNESS
            printf("Called a2dp_signal_connect_req");
            printString("bdaddr", &uu->a2dp_signal_connect_req.bdaddr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 9:
          if(t)
          {
#ifndef TEST_HARNESS
            a2dp_signal_disconnect_req(task);
#endif
#ifdef TEST_HARNESS
            printf("Called a2dp_signal_disconnect_req");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 10:
          if(t)
          {
#ifndef TEST_HARNESS
            a2dp_start_req(task);
#endif
#ifdef TEST_HARNESS
            printf("Called a2dp_start_req");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 11:
          if(t)
          {
#ifndef TEST_HARNESS
            master_reset(task);
#endif
#ifdef TEST_HARNESS
            printf("Called master_reset");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 12:
          if(t)
          {
#ifndef TEST_HARNESS
            a2dp_suspend_req(task);
#endif
#ifdef TEST_HARNESS
            printf("Called a2dp_suspend_req");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 13:
          if(t)
          {
#ifndef TEST_HARNESS
            read_local_bdaddr(task);
#endif
#ifdef TEST_HARNESS
            printf("Called read_local_bdaddr");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 14:
          if(t)
          {
#ifndef TEST_HARNESS
            read_remote_name(task);
#endif
#ifdef TEST_HARNESS
            printf("Called read_remote_name");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 15:
          if(t)
          {
#ifndef TEST_HARNESS
            read_remote_rssi(task);
#endif
#ifdef TEST_HARNESS
            printf("Called read_remote_rssi");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 16:
          if(match1(skip1(getString(skip1(t, e), e, &uu->slc_connect_req.bdaddr), e), e))
          {
#ifndef TEST_HARNESS
            slc_connect_req(task, &uu->slc_connect_req);
#endif
#ifdef TEST_HARNESS
            printf("Called slc_connect_req");
            printString("bdaddr", &uu->slc_connect_req.bdaddr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 17:
          if(t)
          {
#ifndef TEST_HARNESS
            slc_disconnect_req(task);
#endif
#ifdef TEST_HARNESS
            printf("Called slc_disconnect_req");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 18:
          if(match1(skip1(UtilGetNumber(skip1(t, e), e, &uu->set_phonebook_index.index), e), e))
          {
#ifndef TEST_HARNESS
            set_phonebook_index(task, &uu->set_phonebook_index);
#endif
#ifdef TEST_HARNESS
            printf("Called set_phonebook_index");
            printf(" index=%d", uu->set_phonebook_index.index);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 19:
          if(match1(skip1(getString(skip1(t, e), e, &uu->write_pin.pin), e), e))
          {
#ifndef TEST_HARNESS
            write_pin(task, &uu->write_pin);
#endif
#ifdef TEST_HARNESS
            printf("Called write_pin");
            printString("pin", &uu->write_pin.pin);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 20:
          if(t)
          {
#ifndef TEST_HARNESS
            vin_request(task);
#endif
#ifdef TEST_HARNESS
            printf("Called vin_request");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 21:
          if(match1(skip1(getWildString(skip1(t, e), e, &uu->write_local_name.name), e), e))
          {
#ifndef TEST_HARNESS
            write_local_name(task, &uu->write_local_name);
#endif
#ifdef TEST_HARNESS
            printf("Called write_local_name");
            printString("name", &uu->write_local_name.name);
            putchar('\n');
#endif
            continue;
          }
          break;
        default:
          break;
      }
      /*
        The message does not contain a recognised AT command or response.
        Pass the data on to the application to have a go at 
      */
unrecognised:
#ifndef TEST_HARNESS
      handleUnrecognised(s, (uint16) (p-s), task);
#endif
#ifdef TEST_HARNESS
      printf("Called handleUnrecognised\n");
#endif
    }
  }

  return s;
}

/*
read_local_bdaddr
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar D
   MatchChar B
   MatchChar D
   Skip " \t"
   Match "\r\n"


read_remote_rssi
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar D
   MatchChar S
   MatchChar S
   Skip " \t"
   Match "\r\n"


write_pin
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar S
   MatchChar P
   MatchChar I
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString pin
   Skip " \t"
   Match "\r\n"


read_remote_name
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar R
   MatchChar D
   MatchChar N
   MatchChar M
   Skip " \t"
   Match "\r\n"


write_local_name
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar W
   MatchChar R
   MatchChar N
   MatchChar M
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetWildString name
   Skip " \t"
   Match "\r\n"


set_phonebook_index
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar S
   MatchChar P
   MatchChar B
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber index
   Skip " \t"
   Match "\r\n"


slc_connect_req
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar S
   MatchChar C
   MatchChar O
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString bdaddr
   Skip " \t"
   Match "\r\n"


slc_disconnect_req
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar S
   MatchChar D
   MatchChar S
   MatchChar C
   Skip " \t"
   Match "\r\n"


audio_connect_req
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar C
   MatchChar O
   MatchChar N
   Skip " \t"
   Match "\r\n"


audio_disconnect_req
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar A
   MatchChar D
   MatchChar S
   MatchChar C
   Skip " \t"
   Match "\r\n"


virtual_incoming_call
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar I
   MatchChar N
   MatchChar C
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString callerid
   Skip " \t"
   Match "\r\n"


a2dp_signal_connect_req
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar M
   MatchChar C
   MatchChar O
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString bdaddr
   Skip " \t"
   Match "\r\n"


a2dp_signal_connect_req_to_ags
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar M
   MatchChar C
   MatchChar O
   MatchChar N
   Skip " \t"
   Match "\r\n"


a2dp_signal_disconnect_req
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar M
   MatchChar D
   MatchChar S
   MatchChar C
   Skip " \t"
   Match "\r\n"


a2dp_start_req
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar M
   MatchChar P
   MatchChar L
   MatchChar Y
   Skip " \t"
   Match "\r\n"


a2dp_suspend_req
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar M
   MatchChar S
   MatchChar P
   MatchChar D
   Skip " \t"
   Match "\r\n"


sms_new_message_ind
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar C
   MatchChar M
   MatchChar T
   MatchChar I
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetString sender
   Skip " \t"
   SkipOnce ",;"
   Skip " \t"
   GetWildString text
   Skip " \t"
   Match "\r\n"


set_volume_speaker
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar V
   MatchChar G
   MatchChar S
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber volume
   Skip " \t"
   Match "\r\n"


set_volume_microphone
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar V
   MatchChar G
   MatchChar M
   Skip " \t"
   Match "=:"
   Skip " \t"
   GetNumber volume
   Skip " \t"
   Match "\r\n"


master_reset
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar M
   MatchChar R
   MatchChar S
   MatchChar T
   Skip " \t"
   Match "\r\n"


vin_request
   Skip " \t"
   MatchChar A
   MatchChar T
   Skip " \t"
   MatchChar +
   Skip " \t"
   MatchChar V
   MatchChar I
   MatchChar N
   Skip " \t"
   Match "=:"
   Skip " \t"
   Skip "?"
   Skip " \t"
   Match "\r\n"


*/
