/****************************************************************************
Copyright (C) Cambridge Silicon Radio Ltd. 2004-2009
Part of Stereo-Headset-SDK 2009.R2

FILE NAME
	hfp_voice_tag_handler.c

DESCRIPTION
	

NOTES

*/


/****************************************************************************
	Header files
*/
#include "hfp.h"
#include "hfp_private.h"
#include "hfp_parse.h"
#include "hfp_send_data.h"
#include "hfp_voice_tag_handler.h"
#include "hfp_common.h"

#include <panic.h>
#include <string.h>


/* Send a cfm message to the application */
static void sendVoiceTagCfmToApp(HFP *hfp, hfp_lib_status status, uint16 length, uint8 *number)
{
	MAKE_HFP_MESSAGE_WITH_LEN(HFP_VOICE_TAG_NUMBER_CFM, length);
	message->status = status;	
	message->hfp = hfp;
	message->size_phone_number = length;

	if (length)
	{
		memmove(message->phone_number, number, length);
	}
	else
		message->phone_number[0] = 0;
	
	MessageSend(hfp->clientTask, HFP_VOICE_TAG_NUMBER_CFM, message);
}


/****************************************************************************
NAME	
	hfpHandleGetVoiceTagReq

DESCRIPTION
	Issue an "attach number to a voice tag" request to the AG to retrieve
	a phone number.

RETURNS
	void
*/
void hfpHandleGetVoiceTagReq(HFP *hfp)
{
	/* Only send if the AG supports this functionality, otherwise send error */
	if (hfp->agSupportedFeatures & AG_VOICE_TAG)
	{
		static const char binp[] = "AT+BINP=1\r";

		/* Send the AT cmd over the air */
		hfpSendAtCmd(&hfp->task, strlen(binp), binp);
	}
	else
	{
		/* Send an error, the AG does not support this functionality */
		sendVoiceTagCfmToApp(hfp, hfp_fail, 0, 0);
	}
}


/****************************************************************************
NAME	
	hfpHandleGetVoiceTagReq

DESCRIPTION
	Issue an "attach number to a voice tag" request to the AG to retrieve
	a phone number.

RETURNS
	void
*/
void hfpHandleGetVoiceTagReqError(HFP *hfp)
{
	/* Send an error we're in the wrong state */
	sendVoiceTagCfmToApp(hfp, hfp_fail, 0, 0);
}


/****************************************************************************
NAME	
	hfpHandleBinpAtAck

DESCRIPTION
	Received an ack from the app in response to the AT+BINP cmd.

RETURNS
	void
*/
void hfpHandleBinpAtAck(HFP *hfp, hfp_lib_status status)
{
	/* 
		Send cfm to app only if this is an error. If not the response 
		itself will be used to generate the cfm.
	*/
	if (status == hfp_fail)
		sendVoiceTagCfmToApp(hfp, hfp_fail, 0, 0);
}


/****************************************************************************
NAME	
	hfpHandleDataResponse

DESCRIPTION
	Called by the autogenerated parser whanever it parses a +BINP indication
	received from the AG.

AT INDICATION
	+BINP

RETURNS
	void
*/
void hfpHandleDataResponse(Task profileTask, const struct hfpHandleDataResponse *res)
{
	HFP *hfp = (HFP *) profileTask;
	
	checkHfpProfile(hfp->hfpSupportedProfile);
	
	if (res->num.length)
		sendVoiceTagCfmToApp(hfp, hfp_success, res->num.length, (uint8*)res->num.data);	
	else
		sendVoiceTagCfmToApp(hfp, hfp_success, 0, 0);	
}
